/**
 * IEEE 830-1998 SRS format descriptor.
 *
 * Section ids are chosen to match the LEGACY flat resultJson keys exactly
 * (introduction, overallDescription, …) so existing analyses render unchanged through the
 * generic renderer and the legacy generation path stays byte-compatible.
 *
 * tier 'detailed' → full multi-agent pipeline. IEEE generation itself stays on the existing
 * sectional path (this spec drives the frontend renderer, export, and format validation).
 */
export const ieee830 = {
    id: 'ieee830',
    name: 'IEEE 830-1998',
    description: 'Classic Software Requirements Specification (6 chapters + appendices).',
    tier: 'detailed',
    legacyPipeline: true, // generated by the original sectional path, not the descriptor generator
    coverSubtitle: 'Software Requirements Specification',
    requirementModel: 'ieee',
    sections: [
        {
            id: 'introduction', number: '1', title: 'Introduction', kind: 'group',
            guideline: 'Identify the product and revision; describe scope, audience, conventions and references.',
            fields: [
                { id: 'purpose', label: 'Purpose', kind: 'prose', guideline: 'Identify the product and the purpose of this SRS.' },
                { id: 'documentConventions', label: 'Document Conventions', kind: 'prose', guideline: 'Standards, typographic conventions, priority inheritance rules.' },
                { id: 'intendedAudience', label: 'Intended Audience and Reading Suggestions', kind: 'prose', guideline: 'Reader types and a suggested reading sequence.' },
                { id: 'productScope', label: 'Product Scope', kind: 'prose', guideline: 'Benefits, objectives, goals; relate to business strategy.' },
                { id: 'references', label: 'References', kind: 'list', guideline: 'Referenced documents with title, author, version, date, source.' },
            ],
        },
        {
            id: 'overallDescription', number: '2', title: 'Overall Description', kind: 'group',
            guideline: 'Context and high-level view of the product.',
            fields: [
                { id: 'productPerspective', label: 'Product Perspective', kind: 'prose' },
                { id: 'productFunctions', label: 'Product Functions', kind: 'list' },
                { id: 'userClassesAndCharacteristics', label: 'User Classes and Characteristics', kind: 'user-classes' },
                { id: 'operatingEnvironment', label: 'Operating Environment', kind: 'prose' },
                { id: 'designAndImplementationConstraints', label: 'Design and Implementation Constraints', kind: 'list' },
                { id: 'userDocumentation', label: 'User Documentation', kind: 'list' },
                { id: 'assumptionsAndDependencies', label: 'Assumptions and Dependencies', kind: 'list' },
            ],
        },
        {
            id: 'externalInterfaceRequirements', number: '3', title: 'External Interface Requirements', kind: 'group',
            guideline: 'Logical characteristics of every interface.',
            fields: [
                { id: 'userInterfaces', label: 'User Interfaces', kind: 'prose' },
                { id: 'hardwareInterfaces', label: 'Hardware Interfaces', kind: 'prose' },
                { id: 'softwareInterfaces', label: 'Software Interfaces', kind: 'prose' },
                { id: 'communicationsInterfaces', label: 'Communications Interfaces', kind: 'prose' },
            ],
        },
        {
            id: 'systemFeatures', number: '4', title: 'System Features', kind: 'feature-list',
            requirementModel: 'ieee',
            guideline: 'One subsection per feature: Description & Priority, Stimulus/Response, atomic functional requirements.',
        },
        {
            id: 'nonFunctionalRequirements', number: '5', title: 'Other Nonfunctional Requirements', kind: 'group',
            guideline: 'Quality attributes and constraints.',
            fields: [
                { id: 'performanceRequirements', label: 'Performance Requirements', kind: 'list' },
                { id: 'safetyRequirements', label: 'Safety Requirements', kind: 'list' },
                { id: 'securityRequirements', label: 'Security Requirements', kind: 'list' },
                { id: 'softwareQualityAttributes', label: 'Software Quality Attributes', kind: 'list' },
                { id: 'businessRules', label: 'Business Rules', kind: 'list' },
            ],
        },
        {
            id: 'otherRequirements', number: '6', title: 'Other Requirements', kind: 'list',
            guideline: 'Database, internationalization, legal, reuse objectives.',
        },
        {
            id: 'glossary', number: 'A', title: 'Glossary', kind: 'glossary', appendix: true,
            guideline: 'All domain terms, acronyms, abbreviations.',
        },
        {
            id: 'appendices', number: 'B', title: 'Analysis Models', kind: 'diagrams', appendix: true,
            guideline: 'Structural diagrams; select the most fitting Mermaid type per feature/URS.',
        },
    ],
};
