backend:
  - changed-files:
    - any-glob-to-any-file: 'backend/**'

frontend:
  - changed-files:
    - any-glob-to-any-file: 'frontend/**'

cli:
  - changed-files:
    - any-glob-to-any-file: 'cli/**'

ci:
  - changed-files:
    - any-glob-to-any-file: '.github/**'

docs:
  - changed-files:
    - any-glob-to-any-file: 'docs/**'
    - any-glob-to-any-file: '*.md'
