extends: ["spectral:oas", "spectral:asyncapi"]

rules:
  # Enforce operation IDs for better code generation
  operation-operationId: warn
  
  # Require descriptions for better documentation
  info-description: warn
  operation-description: warn
  
  # Ensure all operations have tags for organization
  operation-tags: warn
  
  # Require examples in schemas for better clarity
  oas3-schema-examples: off
  
  # Custom rules can be added here as the API evolves
