import type { AnalysisResult } from "@/types/analysis";
import { getFormatSpec, resolveFormatId } from "@/lib/formats";
import type { RequirementShell } from "@/lib/formats/types";

const isShell = (r: unknown): r is RequirementShell =>
    !!r && typeof r === "object" && "description" in (r as object);

const toStr = (v: unknown): string => {
    if (typeof v === "string") return v;
    if (Array.isArray(v)) return v.map(toStr).join("\n");
    if (v && typeof v === "object" && "content" in (v as Record<string, unknown>)) {
        return String((v as Record<string, unknown>).content || "");
    }
    return "";
};

const getDiagramCode = (d: unknown): string => {
    if (typeof d === "string") return d;
    if (d && typeof d === "object" && "code" in (d as Record<string, unknown>)) {
        return String((d as Record<string, unknown>).code || "");
    }
    return "";
};

/**
 * Generates clean, standard-compliant Markdown for an SRS analysis.
 */
export function exportSrsToMarkdown(
    data: AnalysisResult,
    title: string,
    formatId?: string
): { text: string; filename: string } {
    const resolvedId = formatId || resolveFormatId(data);
    const spec = getFormatSpec(resolvedId);
    const safeTitle = (title || data.projectTitle || "SRS").trim();

    const lines: string[] = [];

    // 1. Header & Metadata
    lines.push(`# ${safeTitle}`);
    lines.push(`**Specification Standard:** ${spec.name} (${spec.id.toUpperCase()})  `);
    lines.push(`**Generated by:** SRA (System Requirements Analyzer)  `);
    lines.push(`**Date:** ${new Date().toISOString().slice(0, 10)}  `);
    lines.push("");
    lines.push("---");
    lines.push("");

    // 2. Introduction
    if (data.introduction) {
        lines.push("## 1. Introduction");
        if (data.introduction.purpose) {
            lines.push("### 1.1 Purpose");
            lines.push(toStr(data.introduction.purpose));
            lines.push("");
        }
        if (data.introduction.documentConventions) {
            lines.push("### 1.2 Document Conventions");
            lines.push(toStr(data.introduction.documentConventions));
            lines.push("");
        }
        if (data.introduction.intendedAudience) {
            lines.push("### 1.3 Intended Audience & Reading Suggestions");
            lines.push(toStr(data.introduction.intendedAudience));
            lines.push("");
        }
        if (data.introduction.productScope) {
            lines.push("### 1.4 Product Scope");
            lines.push(toStr(data.introduction.productScope));
            lines.push("");
        }
    }

    // 3. Overall Description
    if (data.overallDescription) {
        lines.push("## 2. Overall Description");
        if (data.overallDescription.productPerspective) {
            lines.push("### 2.1 Product Perspective");
            lines.push(toStr(data.overallDescription.productPerspective));
            lines.push("");
        }
        if (data.overallDescription.productFunctions) {
            lines.push("### 2.2 Product Functions");
            lines.push(toStr(data.overallDescription.productFunctions));
            lines.push("");
        }
        if (Array.isArray(data.overallDescription.userClassesAndCharacteristics)) {
            lines.push("### 2.3 User Classes & Characteristics");
            data.overallDescription.userClassesAndCharacteristics.forEach((uc) => {
                lines.push(`- **${uc.userClass}:** ${uc.characteristics || ""} `);
            });
            lines.push("");
        }
        if (data.overallDescription.operatingEnvironment) {
            lines.push("### 2.4 Operating Environment");
            lines.push(toStr(data.overallDescription.operatingEnvironment));
            lines.push("");
        }
        if (data.overallDescription.designAndImplementationConstraints) {
            lines.push("### 2.5 Design & Implementation Constraints");
            lines.push(toStr(data.overallDescription.designAndImplementationConstraints));
            lines.push("");
        }
    }

    // 4. System Features / Requirements / User Stories
    if (Array.isArray(data.systemFeatures) && data.systemFeatures.length > 0) {
        lines.push("## 3. System Features & Functional Requirements");
        data.systemFeatures.forEach((feat, idx) => {
            lines.push(`### 3.${idx + 1} ${feat.name}`);
            if (feat.description) lines.push(feat.description);
            lines.push("");

            if (Array.isArray(feat.functionalRequirements) && feat.functionalRequirements.length > 0) {
                lines.push("#### Functional Requirements");
                feat.functionalRequirements.forEach((req, reqIdx) => {
                    if (typeof req === "string") {
                        lines.push(`- **FR-${reqIdx + 1}:** ${req}`);
                    } else if (isShell(req)) {
                        const shell = req as unknown as RequirementShell;
                        lines.push(`- **${shell.id || `FR-${reqIdx + 1}`}:** ${shell.description}`);
                        if (shell.rationale) lines.push(`  - *Rationale:* ${shell.rationale}`);
                        if (shell.fitCriterion) lines.push(`  - *Fit Criterion:* ${shell.fitCriterion}`);
                        if (shell.verificationMethod) lines.push(`  - *Verification:* ${shell.verificationMethod}`);
                        if (shell.source) lines.push(`  - *Source:* ${shell.source}`);
                    }
                });
                lines.push("");
            }
        });
    }

    // 5. External Interface Requirements
    if (data.externalInterfaceRequirements) {
        lines.push("## 4. External Interface Requirements");
        const ei = data.externalInterfaceRequirements;
        if (ei.userInterfaces) {
            lines.push("### 4.1 User Interfaces");
            lines.push(toStr(ei.userInterfaces));
            lines.push("");
        }
        if (ei.hardwareInterfaces) {
            lines.push("### 4.2 Hardware Interfaces");
            lines.push(toStr(ei.hardwareInterfaces));
            lines.push("");
        }
        if (ei.softwareInterfaces) {
            lines.push("### 4.3 Software Interfaces");
            lines.push(toStr(ei.softwareInterfaces));
            lines.push("");
        }
        if (ei.communicationsInterfaces) {
            lines.push("### 4.4 Communications Interfaces");
            lines.push(toStr(ei.communicationsInterfaces));
            lines.push("");
        }
    }

    // 6. Non-Functional Requirements
    if (data.nonFunctionalRequirements) {
        lines.push("## 5. Non-Functional Requirements");
        const nf = data.nonFunctionalRequirements;
        if (nf.performanceRequirements) {
            lines.push("### 5.1 Performance Requirements");
            lines.push(toStr(nf.performanceRequirements));
            lines.push("");
        }
        if (nf.safetyRequirements) {
            lines.push("### 5.2 Safety Requirements");
            lines.push(toStr(nf.safetyRequirements));
            lines.push("");
        }
        if (nf.securityRequirements) {
            lines.push("### 5.3 Security Requirements");
            lines.push(toStr(nf.securityRequirements));
            lines.push("");
        }
        if (nf.softwareQualityAttributes) {
            lines.push("### 5.4 Software Quality Attributes");
            lines.push(toStr(nf.softwareQualityAttributes));
            lines.push("");
        }
    }

    // 7. Glossary
    if (Array.isArray(data.glossary) && data.glossary.length > 0) {
        lines.push("## 6. Glossary & Definitions");
        data.glossary.forEach((item) => {
            lines.push(`- **${item.term}:** ${item.definition}`);
        });
        lines.push("");
    }

    // 8. Architectural Diagrams (Mermaid)
    const models = data.appendices?.analysisModels;
    if (models) {
        lines.push("## 7. Appendices: Architecture & System Models");
        lines.push("");

        const flowchart = getDiagramCode(models.flowchartDiagram);
        if (flowchart) {
            lines.push("### 7.1 System Flowchart");
            lines.push("```mermaid");
            lines.push(flowchart.trim());
            lines.push("```");
            lines.push("");
        }

        const sequence = getDiagramCode(models.sequenceDiagram);
        if (sequence) {
            lines.push("### 7.2 Sequence Diagram");
            lines.push("```mermaid");
            lines.push(sequence.trim());
            lines.push("```");
            lines.push("");
        }

        const erd = getDiagramCode(models.entityRelationshipDiagram);
        if (erd) {
            lines.push("### 7.3 Entity Relationship Diagram");
            lines.push("```mermaid");
            lines.push(erd.trim());
            lines.push("```");
            lines.push("");
        }
    }

    const outputText = lines.join("\n");
    const filename = `${safeTitle.replace(/\s+/g, "_")}_${spec.id.toUpperCase()}.md`;

    return { text: outputText, filename };
}

