import { ieee830 } from './specs/ieee830.js';
import { iso29148 } from './specs/iso29148.js';
import { volere } from './specs/volere.js';
import { agilePrd } from './specs/agilePrd.js';
import { buildFormatSchema } from './schemaBuilder.js';
import { buildFormatGuidelines } from './guidelineBuilder.js';

/**
 * Format registry. Adding an SRS standard = adding a spec file and one entry here; the schema
 * builder, prompt guideline builder, results renderer and export all derive from the spec.
 *
 * @typedef {Object} FormatSection
 * @property {string} id - stable key in resultJson
 * @property {string} number - display number ("1", "1.1", "A")
 * @property {string} title
 * @property {string} kind - prose|list|group|feature-list|requirement-group|user-classes|stakeholders|personas|user-stories|issues|glossary|diagrams
 * @property {string} [guideline]
 * @property {Array} [fields] - for kind 'group'
 * @property {string} [requirementModel] - ieee|volere-shell|story
 * @property {boolean} [appendix]
 *
 * @typedef {Object} FormatSpec
 * @property {string} id
 * @property {string} name
 * @property {string} description
 * @property {'detailed'|'light'} tier
 * @property {boolean} [legacyPipeline] - IEEE only: generated by the original sectional path
 * @property {string} coverSubtitle
 * @property {string} requirementModel
 * @property {string[][]} [chunks] - section-id groups for chunked generation
 * @property {FormatSection[]} sections
 */

const REGISTRY = { ieee830, iso29148, volere, 'agile-prd': agilePrd };

export const DEFAULT_FORMAT_ID = 'ieee830';

export const isValidFormatId = (id) => Object.prototype.hasOwnProperty.call(REGISTRY, id);

export const getFormat = (id) => REGISTRY[id] || REGISTRY[DEFAULT_FORMAT_ID];

export const listFormats = () =>
    Object.values(REGISTRY).map(({ id, name, description, tier }) => ({ id, name, description, tier }));

/** Section-id chunks for generation; falls back to one chunk of all non-appendix sections. */
export const getGenerationChunks = (spec) => {
    if (Array.isArray(spec.chunks) && spec.chunks.length) return spec.chunks;
    return [spec.sections.map((s) => s.id)];
};

export { buildFormatSchema, buildFormatGuidelines };
